"""Battle: the base model against the same model with its adapter.

One prompt, two answers, generated by the one loaded model with the adapter at
strength 0 on one side and at full strength (or whatever the slider says) on
the other. Nothing else differs -- the same system prompt, the same sampling,
the same seed of nothing -- so what differs in the answers is the adapter.

TWO WAYS TO RUN IT

  together   both answers are generated at once, in the server's two slots.
             Each goes at about half speed; they finish together, and the two
             can be read side by side as they are written.
  one by one the base first, then the adapter, each with the whole machine.
             The first answer arrives in half the time.

BLIND

Sides are shuffled and the names hidden until the person votes, so a vote is a
judgment of the answer and not of the label.
"""

from __future__ import annotations

import json
import random
import threading
import time
import uuid
from pathlib import Path
from typing import Callable

from .agent import Profile, Turn
from .engine import Llama


class Battles:
    def __init__(self, path: Path) -> None:
        self.path = path
        self._lock = threading.RLock()

    def _read(self) -> list[dict]:
        try:
            return json.loads(self.path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            return []

    def _write(self, rows: list[dict]) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        temporary = self.path.with_suffix(".tmp")
        temporary.write_text(json.dumps(rows[-300:], ensure_ascii=False, indent=1), encoding="utf-8")
        temporary.replace(self.path)

    def listing(self) -> list[dict]:
        with self._lock:
            return list(reversed(self._read()))

    def save(self, battle: dict) -> None:
        with self._lock:
            rows = [b for b in self._read() if b["id"] != battle["id"]]
            rows.append(battle)
            self._write(rows)

    def vote(self, battle_id: str, vote: str) -> dict:
        if vote not in ("a", "b", "tie", "both_bad"):
            raise ValueError("a vote is a, b, tie or both_bad")
        with self._lock:
            rows = self._read()
            for battle in rows:
                if battle["id"] == battle_id:
                    battle["vote"] = vote
                    self._write(rows)
                    return battle
        raise KeyError(battle_id)

    def delete(self, battle_id: str | None = None) -> None:
        with self._lock:
            self._write([b for b in self._read() if battle_id and b["id"] != battle_id])

    def score(self) -> dict:
        """Wins by contender, whichever side each one happened to be on."""
        tally = {"base": 0, "adapter": 0, "tie": 0, "both_bad": 0, "votes": 0, "battles": 0}
        for battle in self._read():
            tally["battles"] += 1
            vote = battle.get("vote")
            if not vote:
                continue
            tally["votes"] += 1
            if vote in ("tie", "both_bad"):
                tally[vote] += 1
            else:
                tally[battle["sides"][vote]] += 1
        return tally


def run(*, llama: Llama, profile: Profile, settings: dict, prompt: str, mode: str, blind: bool,
        strength: float, emit: Callable[[str, dict], None], cancel: threading.Event) -> dict:
    sides = {"a": "base", "b": "adapter"}
    if blind and random.random() < 0.5:
        sides = {"a": "adapter", "b": "base"}
    battle = {"id": uuid.uuid4().hex[:12], "prompt": prompt, "created": time.time(), "mode": mode,
              "blind": blind, "strength": strength, "sides": sides, "model": profile.name,
              "base_name": profile.base_name, "adapter_name": profile.adapter_name, "vote": None,
              "a": {}, "b": {}}
    emit("battle", {"id": battle["id"], "blind": blind,
                    "sides": None if blind else sides, "mode": mode})

    def one(side: str) -> None:
        contender = sides[side]
        turn = Turn(llama=llama, profile=profile, settings={**settings, "memory": 0}, folder=None,
                    inside=lambda path: Path(path), web=None, history=[], request=prompt, plan=False,
                    emit=lambda event, data: emit(event, {**data, "side": side}), cancel=cancel,
                    ask=lambda key, data: "deny", needs_asking=lambda key: True,
                    adapter=0.0 if contender == "base" else strength)
        emit("side_start", {"side": side})
        message = turn.run(turn.sent_text([]))
        battle[side] = {"text": message.get("content", ""), "think": message.get("think", ""),
                        "stats": message.get("stats", {}), "error": message.get("error", ""),
                        "stopped": bool(message.get("stopped"))}
        emit("side_done", {"side": side, **battle[side]})

    if mode == "parallel":
        workers = [threading.Thread(target=one, args=(side,), daemon=True) for side in ("a", "b")]
        for worker in workers:
            worker.start()
        for worker in workers:
            worker.join()
    else:
        for side in ("a", "b"):
            if cancel.is_set():
                break
            one(side)
    return battle
